# Generated by Django 2.2.1 on 2020-07-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Example1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='example1',
            name='curp',
            field=models.CharField(default='null', max_length=16),
        ),
        migrations.AddField(
            model_name='example1',
            name='direccion',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='example1',
            name='edad',
            field=models.CharField(default='null', max_length=2),
        ),
        migrations.AlterField(
            model_name='example1',
            name='name',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
