# Generated by Django 2.2.1 on 2020-07-04 04:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Example1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='example1',
            name='curp',
            field=models.CharField(default=1, max_length=16, validators=[django.core.validators.MinLengthValidator(16)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='example1',
            name='direccion',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='example1',
            name='edad',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
