# Generated by Django 2.2.1 on 2020-07-04 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Example1', '0002_auto_20200703_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example1',
            name='curp',
            field=models.CharField(default='Null', max_length=255),
        ),
        migrations.AlterField(
            model_name='example1',
            name='direccion',
            field=models.CharField(default='Null', max_length=255),
        ),
        migrations.AlterField(
            model_name='example1',
            name='edad',
            field=models.CharField(default='Null', max_length=255),
        ),
        migrations.AlterField(
            model_name='example1',
            name='name',
            field=models.CharField(default='Null', max_length=255),
        ),
    ]
