# Generated by Django 2.2.1 on 2020-07-04 03:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Example1', '0004_auto_20200703_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example1',
            name='curp',
            field=models.CharField(max_length=16, validators=[django.core.validators.MinValueValidator(16)]),
        ),
        migrations.AlterField(
            model_name='example1',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='example1',
            name='edad',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='example1',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
